List<Map<String, dynamic>> boards = [
  {
    "title": "최병준 선생님 너무 잘생기셨다",
    "content": "최병준 선생님 너무 잘생기셨다",
    "writer": "박현준",
    "date": "2024-05-14",
    "teacher": "최병준",
  },
  {
    "title": "차수민 선생님 너무 잘생기셨다",
    "content": "차수민 선생님 너무 잘생기셨다",
    "writer": "박현준",
    "date": "2024-05-14",
    "teacher": "차수민",
  },
  {
    "title": "박제현 선생님 너무 잘생기셨다",
    "content": "박제현 선생님 너무 잘생기셨다",
    "writer": "박제현",
    "date": "2024-05-14",
    "teacher": "박제현",
  },
  {
    "title": "팬카페 언제함?",
    "content": "팬카페 언제함?",
    "writer": "익명의 팬",
    "date": "2024-05-14",
    "teacher": "최병준",
  },
  {
    "title": "박건우 선생님 너무 잘생기셨다",
    "content": "박건우 선생님 너무 잘생기셨다",
    "writer": "박건우",
    "date": "2024-05-14",
    "teacher": "박건우",
  },
  {
    "title": "최병준 선생님 팬카페 오픈",
    "content": "최병준 선생님 팬카페 오픈",
    "writer": "박현준",
    "date": "2024-05-14",
    "teacher": "최병준",
  },
  {
    "title": "박민하 선생님 플러터 시간",
    "content": "박민하 선생님 플러터 시간",
    "writer": "박민하",
    "date": "2024-05-14",
    "teacher": "박민하",
  },
  {
    "title": "부소마 샤이니",
    "content": "부소마 샤이니",
    "writer": "박현준",
    "date": "2024-05-14",
    "teacher": "부소마 샤이니",
  },
  {
    "title": "부소마 뉴진스",
    "content": "부소마 뉴진스",
    "writer": "박현준",
    "date": "2024-05-14",
    "teacher": "부소마 뉴진스",
  },
  {
    "title": "최병준 선생님 목소리 너무 좋으심",
    "content": "최병준 선생님 목소리 너무 좋으심",
    "writer": "최병준",
    "date": "2024-05-14",
    "teacher": "최병준",
  },
  {
    "title": "박민하 선생님",
    "content": "박민하 선생님",
    "writer": "박현준",
    "date": "2024-05-14",
    "teacher": "박민하",
  }
];
